[localsetup]
autoupdate = true

[ssh]
no_passphrase = true

[git]
overwrite_existing = false
name = "zgtm" 
email = "zgtm@example.com" # Will be overwritten by dotfiles checkout

[rustup]
install_rust = true
update_rust = true

[ubuntu]
remove_snap_and_install_firefox_ppa = true
remove_snap_and_install_firefox_ppa_yes_delete_my_bookmarks_and_everything = true

[signal]
install_signal_desktop_ubuntu = true

[ghostty]
install_ghosty_from_ghostty_ubuntu = true

[restic]
generate_key = true

[uv]
install_astral_sh = true

[xdg-user-dirs]
move_existing = true
desktop = "$HOME/.local/share/desktop"
documents = "$HOME/unterlagen"
downloads = "$HOME/downloads"
music = "$HOME/audio"
pictures = "$HOME/bilder"
publicshare = "$HOME/.local/share/public"
templates = "$HOME/unterlagen/templates"
videos = "$HOME/video"

[packages]
install = [
  "git",
  "fish",
  "curl",
  "htop",
  "jq",
  "age",
  "fd-find",
  "ripgrep",
  "pavucontrol",
  "speedcrunch",
  "redshift",
  "tree",
  
  "build-essential",
  "make", 
  "python-is-python3",
  "cmake",
  "imagemagick",
  "pandoc",
  "whois",
  "wireguard",
  "postgresql-client",

  "emacs-pgtk",
  "elpa-use-package",
  "elpa-rust-mode",
  "elpa-web-mode",
  "elpa-markdown-mode",
  "elpa-projectile",
  "elpa-vertico",
  "elpa-orderless",
  "elpa-spinner",
  "elpa-magit",
  
  "pkg-config", # rust
  "libssl-dev", # rust openssl
]

[[repositories]]
source = "git@git.zgtm.de:zgtm/dotfiles.git"
target = "~/.local/share/dotfiles"
synchronise = true
run_always = "~/.local/share/dotfiles/_bootstrap.sh"

[[repositories]]
source = "git@git.zgtm.de:zgtm/templates.git"
target = "~/unterlagen/vorlagen"
update = true

[[repositories]]
source = "git@git.zgtm.de:zgtm/tools"
target = "~/.local/share/tools"
update = true

[[symlinks]]

